Add the combine feature to support multiple chapters
sillsdev/bible-karaoke pull request #87
Opened 2020-08-15 03:40 UTC by wongpratan

2020-08-15 06:46 UTC, megahirt commented
Hi @wongpratan , this is a good start.  I've finished reading through your code, and I think I understand what you are doing:

- you add a new bbk CLI command called **bbkCombine** which basically wraps a foreach loop around the **bbkConvert** command, taking as input a text file of paths
- you modify the karaoke.js file to run the combine command

Your change adds over 100 lines of code, which is mostly due to adding this feature as a separate command in the CLI.  The actual feature of this change is contained in a few lines of code:

> shell.exec(
>                 `"${ffmpegExe}" -f concat -safe 0 -i "${Options.list}" -c copy "${Options.output}"`,
> 

where Options.list is a string list of paths (joined together properly)

I would like to suggest a simpler approach:

Integrate the above `shell.exec()` directly into the bbkConvert command, with the following features:

- bbkConvert should accept and make use of a list of paths.  This appears to already be true, however the list is never used (only the first item is used).  See line 124: 
> Options.pathFolder = options._.shift();

- rename Options.pathFolder to Options.pathFolders (plural)
- if pathFolders contains one item, just convert it as normal
- add a command line flag, something like --combineOutput which is a boolean.  If this flag is true, then it will determine what happens next
- if pathFolders contains more than one item:
     - if --combineOutput is set to true, then use the ffmpeg command which you wrote (quoted above) to combine them
     - if --combineOutput is set to false, simply loop over the pathFolders and call ffmpeg as if before.

Does this make sense?  In this way, we will add both features (combine into single file + output multiple files) in a lot less code / complexity.  Let me know if you have questions.

2020-08-15 07:57 UTC, wongpratan commented
Thank your @megahirt your review and suggestion.
I'm updating **convert.js** follow your suggestion.
`bbkConvert` has `output` parameter. It is name of a output file.

In case of `--combineOutput` is set to **false**, then loop over the pathFolders.
Should it  generate many output files ? Should we change `output` parameter to be array ?

2020-09-03 09:55 UTC, megahirt commented
@wongpratan my apologies - your reply got lost in my inbox and I didn't see it until just now!

Yes, when --combineOutput is set to false, then you generate multiple files.  The filename should contain the book number and chapter number just as it does now.  Here are some examples:


Here is an example of combining the output into a single file:
```
User selects Mark 1, Mark 2, Mark 3, Mark 4
--combineOutput = true
single filename = Mark1-4.mp4
```

Here is an example of generating multiple files on output:
```
User selects Mark 1, Mark 2, Mark 3, Mark 4
--combineOutput = false
multiple files:
Mark1.mp4
Mark2.mp4
Mark3.mp4
Mark4.mp4
```

These are examples where the default filename is used.  In actuality, the UI lets the user pick a full file path, which includes the filename.  If the user does not take the default filename (say they pick "Bui.mp4" as the output file), then just append a number to each generated file e.g. Bui1.mp4 Bui2.mp4 ...

2020-09-04 07:44 UTC, megahirt reviewed
This is really good!  Just one or two small things.

2020-09-04 07:44 UTC, megahirt commented on public/cli/lib/commands/convert.js
> +                `"${ffmpegExe}" -f concat -safe 0 -i "${outputListFile}" -c copy "${Options.output}"`,
This seems like a good way to combine videos using FFMPEG.  Here is a document which talks about different approaches (for research purposes): https://trac.ffmpeg.org/wiki/Concatenate

2020-09-04 07:44 UTC, megahirt commented on public/cli/lib/commands/convert.js
> +                (err) => {
Would be nice to clean up the outputListFile after rendering (or upon failure).
```
fs.unlink(outputListFile);
```

2020-09-04 07:44 UTC, megahirt commented on public/karaoke.js
> +// })();
need a newline at the end of the file

2020-09-04 07:53 UTC, megahirt requested changes

2020-09-04 07:53 UTC, megahirt commented on public/cli/lib/commands/convert.js
> +    if (Options.combineOutput) {
```
if (Options.combinedOutput && outputFiles.length() > 1) {
```
Only combine output if more than one file is selected

2020-09-04 07:53 UTC, megahirt commented on public/cli/lib/commands/convert.js
> +                (err) => {
```
/// delete intermediate output files after combining them
outputFiles.map((f) => fs.unlink(f),
                (err) => {
                    return err ? fail(err): next();
                });
```

2020-09-04 08:45 UTC, megahirt approved these changes
AFAICT this looks good to me.  Great contribution, Pong!  We will do additional work once this gets merged into master.

2020-09-04 08:45 UTC, megahirt commented on public/karaoke.js
> +hearThisFolder = [
obviously we will need to have more sensible defaults but this is fine for now

2020-09-07 04:23 UTC, merged